#
# CI jobs for Paralympics proto code generation
#
variables:
  CODEGEN_DIR: /codegen

stages:
  - generate

#
# Code generation stage
#

# Generic deploy script included in each codegen job
.generate: &generate
  before_script:
    - mkdir ~/.ssh
    - echo "$DEPLOY_PRIV_KEY" > ~/.ssh/id_rsa
    - chmod -R 0600 ~/.ssh
    - printf "Host github.com\n    StrictHostKeyChecking no" > ~/.ssh/config
  after_script:
    - cd $CODEGEN_DIR
    - git config user.email manoj.kumar@anktech.co.in
    - git config user.name manojkumar2023
    - git add -A
    - |
      if [ "$CI_COMMIT_TAG" != "" ]; then
        echo $CI_COMMIT_TAG
        git tag $CI_COMMIT_TAG
        git push origin $CI_COMMIT_TAG
      else
        git commit -m "Code gen from proto repo @ $CI_COMMIT_SHA"
      fi
      git push origin

# Generate go code and push to gitlab.com
go:
  <<: *generate
  stage: generate
  image: golang:1.13-alpine
  only:
    - develop
    - tags
  script:
    - apk update && apk add make git protobuf protobuf-dev openssh rsync
    - go get github.com/golang/protobuf/protoc-gen-go
    - git clone git@github.com:cohaesus-asm/paralympics-prot.git $CODEGEN_DIR
    - INCLUDE=.:/var/www/html/include make go
    - rsync -aIP --delete --exclude 'README.md' --exclude 'go.*' --exclude '.git/*' codegen/go/ $CODEGEN_DIR

# Generate python code and push to gitlab.com
python27:
  <<: *generate
  stage: generate
  only:
    - develop
    - tags
  image: python:2.7-alpine
  script:
    - apk update && apk add build-base linux-headers make git protobuf protobuf-dev openssh rsync
    - pip install grpcio-tools
    - git clone git@github.com:cohaesus-asm/paralympics-prot.git $CODEGEN_DIR
    - INCLUDE=.:/var/www/html/include make py27
    - rsync -aIP --delete --exclude 'README.md' --exclude '.git/*' codegen/py27/ $CODEGEN_DIR

# Generate typescript code and push to gitlab.com
ts:
  <<: *generate
  stage: generate
  only:
    - develop
    - tags
  image: node:12
  script:
    - apt-get update && apt-get install -y make git unzip rsync python-dev
    - | # Install protoc binary
      curl -OL "https://github.com/google/protobuf/releases/download/v3.9.1/protoc-3.9.1-linux-x86_64.zip" && \
      unzip protoc-3.9.1-linux-x86_64.zip -d protoc3 && \
      mv protoc3/bin/* /usr/local/bin/ && \
      mv protoc3/include/* /usr/local/include/
    - npm --global install ts-protoc-gen
    - npm --global install --unsafe-perm grpc grpc-tools
    - git clone git@github.com:cohaesus-asm/paralympics-prot.git
    - INCLUDE=.:/usr/include make ts
    - rsync -aIP --delete --exclude 'README.md' --exclude 'package.json' --exclude 'grpc.js'  --exclude '.git/*' codegen/ts/ $CODEGEN_DIR